spring.application.name=demo
server.port=8087

spring.datasource.url=jdbc:postgresql://localhost:5432/Mydb
spring.datasource.username=postgres
spring.datasource.password=Keshav@2005
 spring.jpa.properties.hibernate,dialect= org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

spring.security.user.name=admin
